{% set name = "onnxmltools" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/onnx/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: abd9e957ef97a85aa4920bee2d6f2ad46cd42e067a9971469190650641404765

build:
  number: 0
  # skl2onnx (upstream hard dep) is not yet built for py3.14 on pkgs/main
  skip: true  # [py>313]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - onnx >=1.8.1
    - packaging
    - protobuf
    - skl2onnx >=1.4.9

test:
  imports:
    - onnxmltools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://learn.microsoft.com/en-us/windows/ai/windows-ml/onnxmltools
  summary: ONNXMLTools enables conversion of models to ONNX
  description: |
    ONNXMLTools enables you to convert models from different machine learning toolkits into ONNX. Currently the following toolkits are supported:

      - Tensorflow (a wrapper of tf2onnx converter)
      - scikit-learn (a wrapper of skl2onnx converter)
      - Apple Core ML
      - Spark ML (experimental)
      - LightGBM
      - libsvm
      - XGBoost
      - H2O
      - CatBoost
      - Pytorch has its builtin ONNX exporter.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/onnx/onnxmltools
  doc_url: https://github.com/onnx/onnxmltools#readme

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
